### ISSUE TITLE
:robot: Collab discord

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#1]
- [x] Créer un chan dédié
- [x] Récupérer tous les alias
- [x] Inviter tout le monde
- [x] Activer le webook

**Comment by adriens** [comment]
:heavy_check_mark: Inivitation envoyée à @Kevin-Petit

**Comment by adriens** [comment]
test webhook

**Comment by adriens** [comment]
@Kevin-Petit , tu pourras demander  la team de dropper leur alias discord ici :pray:

**Comment by IsoerNC** [comment]
Hello, mon alias discord est le suivant : Alcatraz-NC#8077

**Comment by Davnox900** [comment]
Bonjours voici mon allias discord : Davnox#0139

**Comment by adriens** [comment]
Vous êtes chaud patate les gars :open_mouth:

**Comment by adriens** [comment]
:zap: :point_right: 
https://discord.gg/JmRJBeVF

**Comment by Kevin-Petit** [comment]
Mon alias discord: Captain#2930

**Comment by adriens** [comment]
je crée le salon texte dans la foulée

**Comment by adriens** [comment]
:point_right:  salon textuel https://discord.gg/ZVe5MaZx

**Comment by adriens** [comment]
test webhook salon textuel

**Comment by adriens** [comment]
test

**Comment by adriens** [comment]
test

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/226084144-8e984c36-0b9c-42bf-8b5c-b9f65697dff2.png)

**Comment by adriens** [comment]
je vous ai droppé l'invittaion, je vous laisser faire un coucou sur le chan text :pray:

**Comment by IsoerNC** [comment]
Allo test

**Comment by adriens** [comment]
> Allo test

Roger
