### ISSUE TITLE
:shield: Ajouter CI pour builder en continu (et protéger) sur main :robot: 

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#12]
![image](https://user-images.githubusercontent.com/5235127/232344248-e514de6a-9461-4883-9e50-8180c2514071.png)

**Comment by adriens** [comment]
:information_source: Regarder les GH actions maven, vous verrez c'est très simple à mettre en euvre

**Comment by Kevin-Petit** [comment]
Désormais il y a une GH actions sur le repo.

**Comment by adriens** [comment]
> Désormais il y a une GH actions sur le repo.

Très bien ça :clap:

**Comment by adriens** [comment]
Good job de nettoyer les issues @Kevin-Petit :+1:
