### ISSUE TITLE
:key: Stratégie de Conf clé "X-RAPIDAPI-KEY"

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#20]
# :grey_question: A propos

Actuellement pour lancer l'appli il faut disposer d'un fichier `.env` à la racine du projet, avec la clé `X-RAPIDAPI-KEY` renseignée.
C'est pas embêtant en mode dev puisque on build à la volée... mais si on distribue le `jar`à quelqu'un les choses se compliquement un peu.

:point_right: Le but de cette issue est **d'avancer sur le sujet avec un pattern classique.**

# :dart: Feature request

Au lancement de l'appli : 

1. Checker **dans l'environnement (en mémoire donc)** si une variable `X-RAPIDAPI-KEY` existe
    1. **Elle existe** : on prend la valeur et on l'utilise direct
    2. **Elle n'existe pas** : on va alors chercher dans le `.env` (si pas non plus dans `.env` alors sortir en erreur détaillée)

# :tickets: Issues liées

- https://github.com/adriens/domaine-nc-javafx/issues/6
- https://github.com/adriens/domaine-nc-javafx/pull/4
- https://github.com/adriens/domaine-nc-javafx/pull/16
- https://github.com/adriens/domaine-nc-javafx/issues/11

# :moneybag: Gains

- Je vais partager le `jar` avec des collègues
- Delivery continue de l'app avec le jar comme asset GH

**Comment by adriens** [comment]
hello @Kevin-Petit , je te l'ai assigné, mais c'est toi qui vois qui va travailler dessus (en tant que lead developer cf https://github.com/adriens/domaine-nc-javafx/discussions/15 )

**Comment by adriens** [comment]
:1st_place_medal: Au passage, je sais pas si vous avez fait gaffe, mais... on est arrivés à produire tout ça sans une seule réunion et en pur remote :muscle: C'est vraiment du bon boulot les gars @Kevin-Petit  @IsoerNC  @Davnox900  car c'est pas un exercice facile quand on débute dans le dev :rocket:

**Comment by Kevin-Petit** [comment]
Feature Faite

**Comment by adriens** [comment]
Fermez pas, je vais tester ça ce soir 🙏

**Comment by adriens** [comment]
vous avez testé sous Windows ?

**Comment by adriens** [comment]
(je teserai sr mon 🐧 )

**Comment by Kevin-Petit** [comment]
> vous avez testé sous Windows ?

Oui

**Comment by adriens** [comment]
Je teste ce soir au pire et sinon demain matin... et le fermerai l'issue dans la foulée 🚀

**Comment by adriens** [comment]
@Kevin-Petit  c'est quand la soutenance ? Va falloir qu'on attaque la partie présentation ?

**Comment by adriens** [comment]
C'est parti, je teste from scratch

**Comment by adriens** [comment]
# ↩️  Feedbacks

- Il manque la log dans la console (le GUI seul ne suffit pas, pour investiguer et assurer le support il faut des logs dans console)
- Dans le message d'erreur, rappeler les options pour setter la clé
- Respect du thème black/yellow pour la popup d'erreur

![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/7e1cdec0-1e77-4e0e-a0b5-49c81e43b940)

**Comment by adriens** [comment]
:sos: :point_down: 

- https://github.com/adriens/domaine-nc-javafx/issues/24

**Comment by adriens** [comment]
J'attends  la livraison des fixes pour faire une deuxième session de test

**Comment by Kevin-Petit** [comment]
Update https://github.com/adriens/domaine-nc-javafx/pull/28

**Comment by adriens** [comment]
J'ai reviewé et mergé #28 , je teste from scratch :crossed_fingers:

**Comment by adriens** [comment]
:ok_hand: 

![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/64684ec6-7183-458d-9b40-a3814f9ecb8f)
