### ISSUE TITLE
:calendar: Déterminer date/heure et durée de la soutenance UNC

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#23]

**Comment by adriens** [comment]
Hello @Kevin-Petit , à toi de jouer, on calera tout le reste en fonction de cette échéance

**Comment by adriens** [comment]
Hello @Kevin-Petit  @Davnox900  @IsoerNC , pensez à me donner les billes svp qu'on mette bien en valeur le traval que vous avez fourni :raised_hands:

**Comment by Davnox900** [comment]
excusez moi des billes?

**Comment by adriens** [comment]
> excusez moi des billes?

Une jour et une heure :rofl: 
Comme ça on peut planifier la prépa :100:

**Comment by IsoerNC** [comment]
> > excusez moi des billes?
> 
> Une jour et une heure 🤣 Comme ça on peut planifier la prépa 💯

On nous a prévenu que la soutenance se déroulera le 8 et le 9 Juin mais aucune heure n'a été décidé pour l'instant

**Comment by adriens** [comment]
Ok, bon, ça nous laisse peu de temps pour faire une démo de prezz à blanc : quelles sont vos dispos pour une répét à l'OPT ?

**Comment by adriens** [comment]
Ah ou, ça laisse pas bcp de temps pour faire les simulations :sweat_smile: 

Vous pouvez me ommuniquer : 

- le rapport
- le support de présentation

je ferai la revue avant afin que ce soit le plus clean possible :100:

**Comment by adriens** [comment]
J'ai verrouillé mon agenda en tout cas, je serai là en présenciel :zap:

**Comment by adriens** [comment]
Vous pourrez par exemple simuler vtre présentation en réalisant ceci : 

- https://github.com/adriens/domaine-nc-javafx/issues/39

:point_right: Ainsi, on tire profit au maximum de votre travail

**Comment by IsoerNC** [comment]
Lien vers le powerpoint soutenance : https://www.dropbox.com/scl/fi/ptagjf4abl4c9f2a4rum1/Projet_Tut.pptx?dl=1&rlkey=6szgbiqfybeig2u3m3emt14km

Lien vers le rapport : https://www.dropbox.com/s/q3v79vn2e4i29pq/SoerI_PetitK_DomergueD_Rapport_de_projet_tuteure.pdf?dl=1

**Comment by adriens** [comment]
Parfait, je fais la review de suite :zap:

**Comment by adriens** [comment]
# Feedbacks slideshow

## Slides 

1. Slide 1 : TYPO : "Soutenance de projet tuteure" :arrow_right: "Soutenance de projet tutoré" ou ""tuteuré"
2. Slide 1 : Idée : mettre nos avatars respectifs (ça fait un peu blanc et vide sinon)
3. Slide 4 : JavaFX et consommation d’API :arrow_right: préciser que vous allez consommer une API sur Marketplace, cela mériterait un slide à part entière, peut-etre dans le slide 3, du genre "et l'OPT mes à disposition des APIs publiques, que nous sommes allés consommer", c'est vraiment ça la partie la plus importante dans notre contexte
4. Slide 5 des outils :arrow_right: trop chargé, concentrez vous sur les logos et ajoutez celui de rapidAPI, vous détaillerez à l'oral... en mode deux colonnes ça devrait le faire
5. Slide 7-8 : dégagez-les au profit de la video de démo (pas de démo en live c'est trop risqué t source de stress au mauvais moment) cf #39.
6. Slide 9 : pas forcément utile, mais si vous voulez montrer l'archi du projet, mettez un aperçu javadoc ou README (c'est le mieux)
7. Slide 9 : "Classe main : sert a créer le .jar executable" :arrow_right: non, , avec le manifest, ça aide à savoir comment l'exécuter
8. Slide 10 : Remplacer par javadoc
9. Slide 10 : Vous utilisez Spring, il faut le rajouter au slide de la stack (avec son logo)
10. Slide 11: TYPO  "« Domaine.nc » ou « date.gouv.nc" :arrow_right: `data.gouv.nc`
11. Slide 11 : TYPO " résultat choisis par l’utilisateur" :arrow_right:  résultat choisi (pas de S) par l’utilisateur  
12. Slide 12: "qualité de vie" : User Experience ?
13. Slide 13 : "Fenêtre d’erreur" :arrow_right: Gestion des erreurs et images plus grosses (ajouter à la demo #39 )
14. Slide 14 : Pointer vers la video YT cf #39 
15. Conclusion : mettre en valeur le mode de collab, les issues GH, le rôle de Dev leader, le nombre de réunions, les feedbacks, la protection de la branche main,...

## Général

- Attention car beaucoup de slides (attetion au timing)
- Illustrer davantage
- Aucun screenshot d'issue ou milestone Github
- Plus de visuel/moins austère
- Le mode de collab (pas de réunion par exemple, en full remote, comme un vrai projet open source 100% cloud)
- Comment avez-vous utilisé la documentation de l'API/ sur le marketplace
- A quoi sert cette appli ? Qu'a t-elle de remarquable ?
- ...

**Comment by adriens** [comment]
je passe au rapport :zap:

**Comment by adriens** [comment]
# Feedbacks rapport

- TYPO "ous avons effectués " -> "ous avons effectué"
- "permettant de consulter les noms de DOMAINE.nc en utilisant son API publique."-> permettant de consulter les noms de DOMAINE.nc en utilisant l'API publique mise à disposition sur le marketplace d'APIs de l'OPT
- "application mobile développé en mode Open Innovation" -> application mobile open source développée en mode Open Innovation
- :warning: Screenshots -> mettre ceux en thème dark
- :+1: Très bien le focus sur l'approche thread :+1: 
- "actuellement besoin d’une clé « RAPIDAPI »" -> en détailler un peu le concept (ie. l'API ets gratuite mais nécessite d'êre authentifié)
- :+1: très bien les screenshots dark sur les messages sur la clé d'API
- :heavy_check_mark: OK, vu la transition vers le nouveau thème dark ()ouliez pas l'iconographie
- Pour chaque feature, vous pourrivez pointer l'url de l'issue github correspondante, c'est ce qu'on fait en entreprise
- travail restant : livrer le jar pret à l'emploi cf #21 
- qui réponds à notre sujet de stage -> TYPO "répond"
- TYPO "sujet à de nombreuse optimisation " -> sujet à de nombreuses optimisations
- "Ce projet nous a permis de travailler et d’améliorer nos compétences de coopération ainsi
que de travail à distance étant donné que tout se travail s’est réalisé en distancielle." :clap: OUI :heavy_heart_exclamation:  c'était vraiment la partie la plus importante et qui permet de produire à plusieurs. gros bravo pour cette partie qui va très largement impacter postivement n'élavaluation du projet. Donc vraiment bravo pour cela. Bien accentuer sur l'autoorgansaition, la dynamique des tickets, l'absence de toute réunion. C'est la première étape  pour travailler en nomade digital et sur de l'open source. C'est vraiment le plus important. Donc mention particulère sur le mode de travail asynchrone entre vous et moi... et vous entre vous.
- " indispensable dans la vie d’un informaticien." -> :rofl: Nous ne sommes pas des informaticients... nous sommes des développeurs :sunglasses:

**Comment by adriens** [comment]
vola pour les feedbacks. A vous de jouer

**Comment by adriens** [comment]
:bulb: Egalement, il est une tradition de remercier le tuteur pour le temps investi (le soir et les WEs en général :sweat_smile: )

**Comment by adriens** [comment]
Il manque aussi les ressources url : 

- repo git du projet
- url api marketplace de domaine
- url repo git appli mobile domaine-nc
- ...

**Comment by IsoerNC** [comment]
Je vous envois le lien contenant un .rar qui contient l'intégralité des documents c'est a dire :
-le rapport a jour
-le powerpoint présenté ce matin
-les fiche d'évaluation a remplir

https://www.dropbox.com/s/ozt4g5bre1nopgd/Projet_Tutore_Application_JavaFX_DomaineNC.rar?dl=1

**Comment by adriens** [comment]
Ok, je vais m'en occuper, restera plus que ça : 

- https://github.com/adriens/domaine-nc-javafx/issues/39

Genre semaine pro c'est jouable ?

**Comment by adriens** [comment]
Présentation déroulée ce jour :clap:

**Comment by adriens** [comment]
:pray: Meci pour le slide de fin, je l'ai montrée aux collègues, ils adorent : 

![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/3eddb793-962c-469f-8d5f-5a8a8fddc3a7)
