### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#31]
Feedbacks du main ce soir sous Linux:

- [x] Remplacer "Ouvrir sur Domaine.nc" par le nom de domaine en question... et le rendre cliquable
- [x] Ridet non cliquable
- [x] Layout zebra jaune/noir

**Comment by Kevin-Petit** [comment]
Pour ouvrir les liens il faut double clique, ont dois les passez en clique simple ducoup?

**Comment by adriens** [comment]
AH... hmmm c'est pas facle à deviner en effet... mais j'ai l'impression que ça appelle une commande native... qui ne marche pas sous llinux : 

![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/27a0b4fb-25fa-4f36-aa87-f4c65b225316)

**Comment by Kevin-Petit** [comment]
Pour linux: https://github.com/adriens/domaine-nc-javafx/pull/32

**Comment by adriens** [comment]
Yep, testé validé :ok_hand:
