### ISSUE TITLE
:link: UI > Tweak pour url sur DOMAINE.nc

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#34]
Remplacer : 

![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/bba08e21-1602-4bb5-ac66-dab1789cfd39)

par (car de `opt-et-vous.nc`): 

- [x] Icone de lien (genre navigateur)
- [x] Remplacer "Ouvrir sur Domaine.nc" par "opt-et-vous.nc"

**Comment by Davnox900** [comment]
![image](https://github.com/adriens/domaine-nc-javafx/assets/68035597/82ccea06-26b1-4181-9d4b-d5b8ac0b8f73)

**Comment by adriens** [comment]
C'est nickel et bien joué le logo :100: 
Si tu as mergé, l'isue peut carrément être fermée :zap:

**Comment by adriens** [comment]
:rocket:
