### ISSUE TITLE
:cinema: Démo video commentée 🎞️

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#39]
# :dart: Objectif

Le but de cette issue est que vous me fournissiez une video commentée de votre réalisation.

Cette video a pour but de valoriser votre travail, expliquer votre expérience sur ce projet et ce que, selon vous, cela apporte, ce que vous avez appris, ce que vous ave trouvé cool, ce que vous auriez aimé avoir le temps de faire, etc...

Le public est général et je réutiliserai ce support lorsque je bloggerai dessus :smile_cat: 

En général, ça tient en 15'.

Faites-vous plaisir et bravo pour la collab', vous vous êtes très bien débrouillés :clap: 

:information_source:  Vous pourrez me dropper le `mp4` sur un dropbox ou autre.

**Comment by Kevin-Petit** [comment]
https://www.dropbox.com/s/2pxmgm2quwdynu5/DomaineNcUDH.mp4?dl=1

**Comment by adriens** [comment]
Video ipoalder sur YT, je passe à la suite.
C du très bon boulot, la video est super
