### ISSUE TITLE
:medal_sports: Evaluer la team :people_holding_hands: 

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#42]
# :dart: Actions

Evaluer :

- [x] [Petit Kevin](https://dev.to/kpetit)
- [x] [Domergue David](https://dev.to/davnox900)
- [x] [Soer Irwan](https://dev.to/isoernc)

# :paperclip: Documents

- [Evaluation Tuteur Projet Tutoret.pdf](https://github.com/adriens/domaine-nc-javafx/files/11684151/Evaluation.Tuteur.Projet.Tutoret.pdf)

**Comment by adriens** [comment]
:hand:  @Kevin-Petit on est d'accord pour la soutance c'est une note globale :grey_question:

**Comment by Kevin-Petit** [comment]
Vous devez uniquement noter la fiche "Evaluation du rapport" et  "Evaluation globale du projet" (La fiche de soutenance est en trop)

**Comment by adriens** [comment]
Ok, c'est mis à jour 
![image](https://github.com/adriens/domaine-nc-javafx/assets/5235127/45be91d8-3ae4-4a2d-89a5-423672d60c0e)

**Comment by adriens** [comment]
je le fais maintenant ⚡

**Comment by adriens** [comment]
- https://github.com/adriens/domaine-nc-javafx/issues/44
