### ISSUE TITLE
:camera_flash: Photo de la team :people_holding_hands: 

### ISSUE THREAD

**Issue by adriens** [adriens/domaine-nc-javafx#43]
# :grey_question: A propos

je voulais faire une photo souvenir avec vous à l'UNC ce matin mais j'ai complétement zappé.

# :dart: Actions

Me dropper quelques photos de vous : 

- [x] Sur votre (ou vos) spots préférés de la FAC
- [x] Une photo devant le logo de l'OPT à l'entrée de la Fac, histoire de nous faire un sovenir sympa

**Comment by Kevin-Petit** [comment]
![IMG_20230609_130800](https://github.com/adriens/domaine-nc-javafx/assets/74395438/5340592e-3c25-4686-8844-756cde911403)

![1686277375577](https://github.com/adriens/domaine-nc-javafx/assets/74395438/384eccb8-0e00-4ba0-8add-8d78fe71242c)

**Comment by adriens** [comment]
Super stylées les photos :star_struck: 
Merci les gars :pray:

**Comment by adriens** [comment]
:thought_balloon: Vous deviez pas être en vacances :grey_question:
