### ISSUE TITLE
🖼️ Interface

### ISSUE THREAD

**Issue by Kevin-Petit** [adriens/domaine-nc-javafx#5]
Avancement de l'interface: 

- [x] Interface de base
- [x] Interface dynamique
- [x] Link un CSS
- [x] Beautify
- [x] Ajout de la vue détailer d'un domaine

**Comment by Kevin-Petit** [comment]
Interface de base  > 05/04/2023 
Link un CSS > 14/04/2023

**Comment by adriens** [comment]
:100: Bravo pour le ticket très complet et le suivi : 

![image](https://user-images.githubusercontent.com/5235127/232259933-c844f368-d059-4a24-bdae-c57a02f0b1a4.png)

:bulb: Oubliez pas que vous pouvez transformer les items en issues de petite granuralité : 


https://youtu.be/BplF7vHXewA


C'est super pratique, nous le faisons en permance sur les projets au sein de mon équipe à l'opt.

**Comment by adriens** [comment]
:bulb: Egalement depuis une issue, tu peux créer une branche directement. Quand tu merges la brache, ça ferme automatiquement l'issue :smile:

**Comment by adriens** [comment]
:zap:
