### ISSUE TITLE
🔌Consommation API

### ISSUE THREAD

**Issue by Kevin-Petit** [adriens/domaine-nc-javafx#6]
Avancement Consommation API :

- [x] Clef API dans une variable d'environnement
- [x] #7
- [x]  Consommation de GET Domaine

**Comment by Kevin-Petit** [comment]
Pour l'utiliser il faut créer un fichier .env dans la racine du projet avec:
```shell
X-RAPIDAPI-KEY=Votre_Clef_API
```
Pour le moment il y a une méthode getDomaine() qui permet de récupéré la liste des domaines

**Comment by adriens** [comment]
Good, pouvez-vous le documenter sur le README, comme un prérequis :grey_question: :pray:

**Comment by adriens** [comment]
> Pour le moment il y a une méthode getDomaine() qui permet de récupéré la liste des domaines

C'est un très bon début. hésitez pas à dropper sur cette issue même : 

- des screenshots
- de la video de petites démos

Nous la valoriserons :muscle:

**Comment by adriens** [comment]
:ok_man:  @Kevin-Petit , je vois que tu utilises les check pour mesurer la progression du projet : 

![image](https://user-images.githubusercontent.com/5235127/232259900-32d1e937-8ec3-4206-abfb-a04e30dda7be.png)

:point_right: c'est du **très bon boulot** :clap:

**Comment by Kevin-Petit** [comment]
getDomaine() Permet de récupéré la Liste des domaines depuis l'API public

Exemple d'utilisation :

![4554d54g5f4g2fsg1s](https://user-images.githubusercontent.com/74395438/232263929-a0b76edf-ce3d-476d-856c-42c185876f79.png)

- Création d'un objet Request
- Appel de getDomaine()
- Affichage nom et extensions des domaines dans la console

**Comment by adriens** [comment]
:bulb: Pour partager des codes snippets, privilégier le code aux images (les images ne sont pas indexées) : 

```java
public status void main(String[] args){
// Do something...
}
```

**Comment by adriens** [comment]
:point_right:  Pour logger, privilégier [logback](https://logback.qos.ch/) à `System.out`

**Comment by Kevin-Petit** [comment]
getDomaineInfo(String domaineName) Permet de récupéré les information sur le domaine depuis l'API public

Exemple d'utilisation :
```java
//Création d'un objet Request
Request request = new Request();
//Appel de getDomaineInfo(String domaineName) 
DomaineInfoEntity domaineInfo = request.getDomaineInfo("1012");
```

**Comment by adriens** [comment]
:ok_man: 
Bon we @Kevin-Petit :smile_cat:

**Comment by adriens** [comment]
:+1:
