### ISSUE TITLE
📡Liaison API/Interface

### ISSUE THREAD

**Issue by Kevin-Petit** [adriens/domaine-nc-javafx#8]
Avancement : 

- [x] Lier GET ALL domaines
- [x] Méthode de recherche
- [x] Lier GET Domaine
- [x] Sélection d'un domaine
- [x] Affichage des détails

**Comment by IsoerNC** [comment]
Pour l'instant la méthode de recherche se contente de vérifier si la chaine de charactère entré dans la barre de recherche existe dans le nom du nom de domaine

**Comment by Kevin-Petit** [comment]
J'ai amélioré la méthode de recherche, elle fonctionne normalement désormais.

**Comment by adriens** [comment]
Jolie collab @IsoerNC  @Kevin-Petit  :muscle: 

> Pour l'instant la méthode de recherche se contente de vérifier si la chaine de charactère entré dans la barre de recherche existe dans le nom du nom de domaine.

Oui, et c'est une très bonne approche car cela apporter déja de la valeur au projet :100: 

> On ne dois entrer dans la zone de recherche uniquement le nom de domaine sans l'extension.

N"hésitez pas à vous inspirer de l'appli mobile [domaine-nc-mobile](https://github.com/lschaeffer313/domaine-nc-mobile)

**Comment by adriens** [comment]
En tout cas les tests de connexion sont :ok:

**Comment by Davnox900** [comment]
Ajout de l'affichage des information d'un domaine dans une autre fenêtre.

**Comment by adriens** [comment]
> Ajout de l'affichage des information d'un domaine dans une autre fenêtre.

hello @Davnox900 , as-tu des screenshots à se mettre sous la dent ? :pray:

**Comment by Davnox900** [comment]
![capture](https://github.com/adriens/domaine-nc-javafx/assets/68035597/99336041-a451-4621-b520-11c91d225c3d)

voila

**Comment by adriens** [comment]
Cool, reste plus que les labels alors ?

**Comment by Davnox900** [comment]
normalement oui

**Comment by adriens** [comment]
Cool :ok_man:

**Comment by Kevin-Petit** [comment]
Update :

![123123132123](https://github.com/adriens/domaine-nc-javafx/assets/74395438/88196743-6275-48aa-b866-225544590c5d)

**Comment by adriens** [comment]
Faudrait voir si on peut pas transformer la liste de dns en u widget de type liste ou tableau :thinking:

**Comment by adriens** [comment]
C'est :100: :+1: , je ferme
